// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrapData() {
    return window["go"]["main"]["App"]["GetBootstrapData"]();
}

export function GetWorkspaceState() {
    return window["go"]["main"]["App"]["GetWorkspaceState"]();
}

export function SaveConnection(arg1) {
    return window["go"]["main"]["App"]["SaveConnection"](arg1);
}

export function DeleteConnection(arg1) {
    return window["go"]["main"]["App"]["DeleteConnection"](arg1);
}

export function TestConnection(arg1) {
    return window["go"]["main"]["App"]["TestConnection"](arg1);
}

export function SaveAISettings(arg1) {
    return window["go"]["main"]["App"]["SaveAISettings"](arg1);
}

export function ClearAIAPIKey() {
    return window["go"]["main"]["App"]["ClearAIAPIKey"]();
}

export function GetExplorerTree(arg1) {
    return window["go"]["main"]["App"]["GetExplorerTree"](arg1);
}

export function GetTableDetail(arg1) {
    return window["go"]["main"]["App"]["GetTableDetail"](arg1);
}

export function GetTableRowCounts(arg1) {
    return window["go"]["main"]["App"]["GetTableRowCounts"](arg1);
}

export function ExecuteQuery(arg1) {
    return window["go"]["main"]["App"]["ExecuteQuery"](arg1);
}

export function PreviewTableData(arg1) {
    return window["go"]["main"]["App"]["PreviewTableData"](arg1);
}

export function GetQueryHistory(arg1) {
    return window["go"]["main"]["App"]["GetQueryHistory"](arg1);
}

export function RenameTable(arg1) {
    return window["go"]["main"]["App"]["RenameTable"](arg1);
}

export function GetFieldDictionarySuggestion(arg1) {
    return window["go"]["main"]["App"]["GetFieldDictionarySuggestion"](arg1);
}

export function GenerateFieldComment(arg1) {
    return window["go"]["main"]["App"]["GenerateFieldComment"](arg1);
}

export function OptimizeSQL(arg1) {
    return window["go"]["main"]["App"]["OptimizeSQL"](arg1);
}

export function BeautifySQL(arg1) {
    return window["go"]["main"]["App"]["BeautifySQL"](arg1);
}

export function AnalyzeSQL(arg1) {
    return window["go"]["main"]["App"]["AnalyzeSQL"](arg1);
}

export function ChatWithDatabase(arg1) {
    return window["go"]["main"]["App"]["ChatWithDatabase"](arg1);
}

export function RepairChatSQL(arg1) {
    return window["go"]["main"]["App"]["RepairChatSQL"](arg1);
}

export function GetStorageInfo() {
    return window["go"]["main"]["App"]["GetStorageInfo"]();
}

export function SetStoragePath(arg1) {
    return window["go"]["main"]["App"]["SetStoragePath"](arg1);
}

export function GrantStoragePermission() {
    return window["go"]["main"]["App"]["GrantStoragePermission"]();
}

export function ClearStorageData(arg1) {
    return window["go"]["main"]["App"]["ClearStorageData"](arg1);
}

export function SelectStorageDirectory() {
    return window["go"]["main"]["App"]["SelectStorageDirectory"]();
}

export function ExportTextFile(arg1) {
    return window["go"]["main"]["App"]["ExportTextFile"](arg1);
}
