// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSQL(arg1) {
  return window['go']['main']['App']['AnalyzeSQL'](arg1);
}

export function BatchExecute(arg1) {
  return window['go']['main']['App']['BatchExecute'](arg1);
}

export function BeautifySQL(arg1) {
  return window['go']['main']['App']['BeautifySQL'](arg1);
}

export function BrowseRedisKeys(arg1) {
  return window['go']['main']['App']['BrowseRedisKeys'](arg1);
}

export function BuildAlterSQL(arg1) {
  return window['go']['main']['App']['BuildAlterSQL'](arg1);
}

export function BuildCreateTableSQL(arg1) {
  return window['go']['main']['App']['BuildCreateTableSQL'](arg1);
}

export function BuildPartitionDDL(arg1) {
  return window['go']['main']['App']['BuildPartitionDDL'](arg1);
}

export function ChatWithDatabase(arg1) {
  return window['go']['main']['App']['ChatWithDatabase'](arg1);
}

export function CleanupIdleConnections() {
  return window['go']['main']['App']['CleanupIdleConnections']();
}

export function ClearAIAPIKey() {
  return window['go']['main']['App']['ClearAIAPIKey']();
}

export function ClearStorageData(arg1) {
  return window['go']['main']['App']['ClearStorageData'](arg1);
}

export function CreateDatabase(arg1) {
  return window['go']['main']['App']['CreateDatabase'](arg1);
}

export function CreateTable(arg1) {
  return window['go']['main']['App']['CreateTable'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function ExecutePartitionAction(arg1) {
  return window['go']['main']['App']['ExecutePartitionAction'](arg1);
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function ExecuteTransaction(arg1) {
  return window['go']['main']['App']['ExecuteTransaction'](arg1);
}

export function ExportTextFile(arg1) {
  return window['go']['main']['App']['ExportTextFile'](arg1);
}

export function FillTableData(arg1) {
  return window['go']['main']['App']['FillTableData'](arg1);
}

export function GenerateFieldComment(arg1) {
  return window['go']['main']['App']['GenerateFieldComment'](arg1);
}

export function GenerateIndexName(arg1) {
  return window['go']['main']['App']['GenerateIndexName'](arg1);
}

export function GetBootstrapData() {
  return window['go']['main']['App']['GetBootstrapData']();
}

export function GetConnectionPoolStatus() {
  return window['go']['main']['App']['GetConnectionPoolStatus']();
}

export function GetCrashLogs() {
  return window['go']['main']['App']['GetCrashLogs']();
}

export function GetDatabaseUsers(arg1) {
  return window['go']['main']['App']['GetDatabaseUsers'](arg1);
}

export function GetExplorerTree(arg1) {
  return window['go']['main']['App']['GetExplorerTree'](arg1);
}

export function GetFieldDictionarySuggestion(arg1) {
  return window['go']['main']['App']['GetFieldDictionarySuggestion'](arg1);
}

export function GetPerformanceMetrics(arg1) {
  return window['go']['main']['App']['GetPerformanceMetrics'](arg1);
}

export function GetQueryHistory(arg1) {
  return window['go']['main']['App']['GetQueryHistory'](arg1);
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function GetTableDetail(arg1) {
  return window['go']['main']['App']['GetTableDetail'](arg1);
}

export function GetTablePartitions(arg1) {
  return window['go']['main']['App']['GetTablePartitions'](arg1);
}

export function GetTableRowCounts(arg1) {
  return window['go']['main']['App']['GetTableRowCounts'](arg1);
}

export function GetWorkspaceState() {
  return window['go']['main']['App']['GetWorkspaceState']();
}

export function GrantStoragePermission() {
  return window['go']['main']['App']['GrantStoragePermission']();
}

export function ImportFile(arg1) {
  return window['go']['main']['App']['ImportFile'](arg1);
}

export function OptimizeSQL(arg1) {
  return window['go']['main']['App']['OptimizeSQL'](arg1);
}

export function PreviewImport(arg1) {
  return window['go']['main']['App']['PreviewImport'](arg1);
}

export function PreviewSmartFillSQL(arg1) {
  return window['go']['main']['App']['PreviewSmartFillSQL'](arg1);
}

export function PreviewTableData(arg1) {
  return window['go']['main']['App']['PreviewTableData'](arg1);
}

export function RenameTable(arg1) {
  return window['go']['main']['App']['RenameTable'](arg1);
}

export function RepairChatSQL(arg1) {
  return window['go']['main']['App']['RepairChatSQL'](arg1);
}

export function SaveAISettings(arg1) {
  return window['go']['main']['App']['SaveAISettings'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SelectImportFile() {
  return window['go']['main']['App']['SelectImportFile']();
}

export function SelectStorageDirectory() {
  return window['go']['main']['App']['SelectStorageDirectory']();
}

export function SetStoragePath(arg1) {
  return window['go']['main']['App']['SetStoragePath'](arg1);
}

export function SmartFillTableData(arg1) {
  return window['go']['main']['App']['SmartFillTableData'](arg1);
}

export function SummarizeChatResult(arg1) {
  return window['go']['main']['App']['SummarizeChatResult'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
