// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {appmeta} from '../models';
import {store} from '../models';

export function AnalyzeSQL(arg1:string):Promise<workspace.SQLAnalysis>;

export function BeautifySQL(arg1:workspace.SQLOptimizeRequest):Promise<workspace.SQLOptimizeResult>;

export function BrowseRedisKeys(arg1:workspace.RedisKeyBrowseRequest):Promise<workspace.RedisKeyBrowseResult>;

export function ChatWithDatabase(arg1:workspace.ChatDatabaseRequest):Promise<workspace.ChatDatabaseResponse>;

export function ClearAIAPIKey():Promise<workspace.AISettingsView>;

export function ClearStorageData(arg1:string):Promise<workspace.SetStoragePathResult>;

export function CreateDatabase(arg1:workspace.CreateDatabaseRequest):Promise<workspace.CreateDatabaseResult>;

export function CreateTable(arg1:workspace.CreateTableRequest):Promise<workspace.CreateTableResult>;

export function DeleteConnection(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:workspace.QueryRequest):Promise<workspace.QueryResult>;

export function ExportTextFile(arg1:workspace.ExportFileRequest):Promise<workspace.ExportFileResult>;

export function FillTableData(arg1:workspace.FillTableRequest):Promise<workspace.FillTableResult>;

export function GenerateFieldComment(arg1:workspace.AIFieldCommentRequest):Promise<workspace.AIFieldCommentResult>;

export function GenerateIndexName(arg1:any):Promise<any>;

export function GetBootstrapData():Promise<appmeta.ProductOverview>;

export function GetCrashLogs():Promise<Array<store.CrashLogEntry>>;

export function GetExplorerTree(arg1:workspace.ExplorerRequest):Promise<workspace.ExplorerTree>;

export function GetFieldDictionarySuggestion(arg1:workspace.FieldDictionaryRequest):Promise<workspace.FieldDictionarySuggestion>;

export function GetQueryHistory(arg1:string):Promise<Array<workspace.HistoryItem>>;

export function GetStorageInfo():Promise<workspace.StorageInfoView>;

export function GetTableDetail(arg1:workspace.TableDetailRequest):Promise<workspace.TableDetail>;

export function GetTableRowCounts(arg1:workspace.TableRowCountRequest):Promise<workspace.TableRowCountResult>;

export function GetWorkspaceState():Promise<workspace.WorkspaceState>;

export function GrantStoragePermission():Promise<workspace.SetStoragePathResult>;

export function OptimizeSQL(arg1:workspace.SQLOptimizeRequest):Promise<workspace.SQLOptimizeResult>;

export function PreviewSmartFillSQL(arg1:any):Promise<any>;

export function PreviewTableData(arg1:workspace.TablePreviewRequest):Promise<workspace.QueryResult>;

export function RenameTable(arg1:workspace.RenameTableInput):Promise<workspace.RenameTableResult>;

export function RepairChatSQL(arg1:workspace.ChatRepairRequest):Promise<workspace.ChatDatabaseResponse>;

export function SaveAISettings(arg1:workspace.AISettingsInput):Promise<workspace.AISettingsView>;

export function SaveConnection(arg1:workspace.ConnectionInput):Promise<workspace.ConnectionProfile>;

export function SelectStorageDirectory():Promise<string>;

export function SetStoragePath(arg1:string):Promise<workspace.SetStoragePathResult>;

export function SmartFillTableData(arg1:workspace.SmartFillTableRequest):Promise<workspace.SmartFillTableResult>;

export function SummarizeChatResult(arg1:workspace.ChatResultSummaryRequest):Promise<workspace.ChatResultSummary>;

export function TestConnection(arg1:workspace.ConnectionInput):Promise<workspace.ConnectionTestResult>;
