// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrapData(): Promise<any>;
export function GetWorkspaceState(): Promise<any>;
export function SaveConnection(arg1: any): Promise<any>;
export function DeleteConnection(arg1: string): Promise<void>;
export function TestConnection(arg1: any): Promise<any>;
export function SaveAISettings(arg1: any): Promise<any>;
export function ClearAIAPIKey(): Promise<any>;
export function GetExplorerTree(arg1: any): Promise<any>;
export function GetTableDetail(arg1: any): Promise<any>;
export function GetTableRowCounts(arg1: any): Promise<any>;
export function ExecuteQuery(arg1: any): Promise<any>;
export function PreviewTableData(arg1: any): Promise<any>;
export function GetQueryHistory(arg1: string): Promise<any>;
export function RenameTable(arg1: any): Promise<any>;
export function GetFieldDictionarySuggestion(arg1: any): Promise<any>;
export function GenerateFieldComment(arg1: any): Promise<any>;
export function OptimizeSQL(arg1: any): Promise<any>;
export function BeautifySQL(arg1: any): Promise<any>;
export function AnalyzeSQL(arg1: string): Promise<any>;
export function ChatWithDatabase(arg1: any): Promise<any>;
export function RepairChatSQL(arg1: any): Promise<any>;
export function ExportTextFile(arg1: any): Promise<any>;
